name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Run terragrunt validate
    runs-on: ubuntu-latest
    env:
      TG_PROVIDER_CACHE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure code is formatted
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: "1.12.2"
          tg_version: "0.82.2"
          tg_command: "hcl fmt --check"

      - name: Validate Terragrunt manifests
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: "1.12.2"
          tg_version: "0.82.2"
          tg_command: "hcl validate"

      - name: Validate Terragrunt configuration
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: "1.12.2"
          tg_version: "0.82.2"
          tg_command: "run validate --all"
